rule final:
    input:"test.fasta.fubar.csv"

rule hyphy:
    input:
        tree="test.tree",
        align="test.fasta"
    output:
        "test.fasta.fubar.csv"
    shell:
        "(echo 1; echo 1;echo {input.align}; echo {input.tree}; echo 20;echo echo 5; echo 2000000; echo 1000000;echo 100;echo 0.5 )|HYPHYMP /home/usr/hyphy/res/TemplateBatchFiles/FUBAR.bf"
